### ISSUE TITLE
TeamCity reports less tests than there actually are with multiple 'describe' levels

### ISSUE THREAD

**Issue by miroslawmajka** [balassy/mocha-allure-teamcity-reporter#1]
We've come across an issue with TeamCity only reporting a limited number of Mocha tests when several 'describe' levels are present. We use this in conjunction with mocha-each:

const withThese = require('mocha-each');

```
describe('@tag1 @tag2 When I do A', function() {
    describe('@tag3 with params B', function() {
        describe('@tag4 and expect C', function() {
            let correctParameters = [
                [1],
                [2],
                [3]
            ];
            withThese(correctParameters )
                .it('does D with %s', (param1) => {
        });
    });
});
```

When this is run locally using the spec reported the amount of tests is correct but within TeamCity the summary is wrong. The log lists all the tests but the ultimate result of the test run is incomplete. It looks like only top-level suites are counted.

**Comment by balassy** [comment]
Thanks for reporting this issue, Miroslaw. I used this reporter with multiple `describe` blocks, but I have never experienced this problem. 
However, I saw this counting problem in other cases, when TeamCity could not differentiate between multiple test cases, because their full names (with the name of the parent describe blocks) were identical. The same happens when you run the same test cases multiple times. 
I have not used `mocha-each` before, are you sure it doesn't have any side effect like that?

**Comment by miroslawmajka** [comment]
Thanks for the reply. We've tried this with different scenarios, with and without `mocha-each`, TeamCity never seems to be reporting the correct number of tests when we got many levels of describe. I can provide you with a valid working example in my private GitHub repo when I get a minute. At the time we're going with the `mocha-teamcity-reporter` (https://github.com/travisjeffery/mocha-teamcity-reporter/issues/26) which seems to have stalled development but the reported number of tests is more accurate at the moment. I've reported an almost identical issue there but all quiet so far.

We've tried modifying the code as for the mocha reporter events but TeamCity still reports less tests than declared.

**Comment by balassy** [comment]
Miroslaw, could you please send the log of the test suite? If you run this reporter locally, it should print the log to the console, in TeamCity you can find it under the the Log tab.

**Comment by miroslawmajka** [comment]
Apologies  for the late reply. We'll have some time for this issue soon. I don't want to send the entire automation log with all the sensitive data so I'll come up with an experimental test suite that illustrates the counting discrepancy. Thank you for your patience.

**Comment by balassy** [comment]
That's okay, and I thank you, Miroslaw.

**Comment by miroslawmajka** [comment]
I'm sorry I couldn't find the time to deal with this issue. We've decided to refactor our Mocha test suite to have only one level of 'describe' statements and TeamCity seems to be counting that fine. Also we are trying to move away from Mocha for most of our test scenarios in favour of Cucumber. I'm going to close this issue unless someone else really wants to carry on. Thanks for your help.

**Comment by balassy** [comment]
Thank you, Miroslaw.
